### ISSUE TITLE
simplepro 手写的actions 方法点击不执行好像

### ISSUE THREAD

**Issue by zhc1208420887** [newpanjing/simplepro#1]
还有图片字段好像也不支持

Traceback (most recent call last):
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/django/core/handlers/base.py", line 106, in _get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/simplepro/middlewares.py", line 19, in process_view
    return backends .pre_process (request ,view_func )#line:28
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/simplepro/backends.py", line 79, in pre_process
    return process_list (request ,view_func .model_admin )#line:105
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/simplepro/backends.py", line 129, in process_list
    return OO000O0OO000OO0O0 [OO0000OOOOOOO0O0O ](request ,model_admin )#line:185
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/simplepro/backends.py", line 291, in list_data
    return write (OOO00O0O0O000O00O )#line:466
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/simplepro/utils.py", line 142, in write
    return HttpResponse (json .dumps (OOOOOO0OOOOO00OOO ,cls =LazyEncoder ),content_type ='application/json')#line:218
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/simplepro/utils.py", line 17, in default
    return super (LazyEncoder ,self ).default (obj )#line:24
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ImageFieldFile' is not JSON serializable
ERROR basehttp 154 "POST /be_xftm/mhxy_check/chdetailcheck/ HTTP/1.1" 500 175167

**Comment by zhc1208420887** [comment]
有时第一次点击编辑 刚打开会提示一个操作成功

**Comment by zhc1208420887** [comment]
def make_transfer(self, request, queryset):
        try:
            if queryset:
                queryset.update(section=4)
                messages.add_message(request, messages.SUCCESS, '操作成功')
        except Exception:
            messages.add_message(request, messages.ERROR, '操作失败,请重试')
好像这样update

**Comment by zhc1208420887** [comment]
是自定义按钮 里边获取没有queryset了！
