### ISSUE TITLE
模型继承的类　ａｄｍｉｎ无法展示　如下：

### ISSUE THREAD

**Issue by zhc1208420887** [newpanjing/simplepro#15]
ｍｏｄｅｌｓ：
class Demo1(models.Model):
    a = models.CharField(
        blank=True,
        null=True,
        max_length=30,
        verbose_name='1'
    )
    b = models.CharField(
        blank=True,
        null=True,
        max_length=30,
        verbose_name='2'
    )
    verbose_name = 'Demo1'
    verbose_name_plural = verbose_name
    
class Demo2(Demo1):
    class Meta:
        verbose_name = 'Demo2'
        verbose_name_plural = verbose_name
ａｄｍｉｎ：
        
class Demo1Admin(admin.ModelAdmin):
    list_display = ('a','b')
    
class Demo2Admin(admin.ModelAdmin):
    list_display = ('a','b')
    list_display_links = None

admin.site.register(models.Demo1, Demo1Admin)
admin.site.register(models.Demo2, Demo2Admin)

就报这个错：
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
    return self.application(environ, start_response)
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/django/views/debug.py", line 94, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/django/views/debug.py", line 333, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/django/views/debug.py", line 264, in get_traceback_data
    frames = self.get_traceback_frames()
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/django/views/debug.py", line 422, in get_traceback_frames
    filename, lineno, 7, loader, module_name,
  File "/home/xftm/.virtualenvs/evn_django/lib/python3.6/site-packages/django/views/debug.py", line 383, in _get_lines_from_file
    context_line = source[lineno]
IndexError: list index out of range
ERROR basehttp 154 "POST /be_xftm/lingshi_sold/lingshi_check1/ HTTP/1.1" 500 59

**Comment by newpanjing** [comment]
请升级至simplepro 1.0

pip3 install simplepro==1.0
